"""empty message

Revision ID: 455c24539b3f
Revises: 7298b7266cfb
Create Date: 2019-01-31 09:57:40.021533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455c24539b3f'
down_revision = '7298b7266cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('izlet', sa.Column('slika', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('slika', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_slika'), 'user', ['slika'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_slika'), table_name='user')
    op.drop_column('user', 'slika')
    op.drop_column('izlet', 'slika')
    # ### end Alembic commands ###
