"""izlet table

Revision ID: 7298b7266cfb
Revises: cd1fd3e7ff53
Create Date: 2019-01-30 10:56:21.078855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7298b7266cfb'
down_revision = 'cd1fd3e7ff53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('izlet', sa.Column('rezervirano', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('izlet', 'rezervirano')
    # ### end Alembic commands ###
