"""izlet table

Revision ID: 7927ed6a5d27
Revises: b57d314b20a3
Create Date: 2019-01-25 10:58:59.577760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7927ed6a5d27'
down_revision = 'b57d314b20a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('izlet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mjesto', sa.String(length=140), nullable=True),
    sa.Column('cijena', sa.Integer(), nullable=True),
    sa.Column('trajanje', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_table('izlet')
    # ### end Alembic commands ###
