"""users table

Revision ID: 9d556144bfda
Revises: b6790b06d443
Create Date: 2019-01-25 10:13:52.974381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d556144bfda'
down_revision = 'b6790b06d443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ime', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('prezime', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('spol', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_ime'), 'user', ['ime'], unique=False)
    op.create_index(op.f('ix_user_prezime'), 'user', ['prezime'], unique=False)
    op.create_index(op.f('ix_user_spol'), 'user', ['spol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_spol'), table_name='user')
    op.drop_index(op.f('ix_user_prezime'), table_name='user')
    op.drop_index(op.f('ix_user_ime'), table_name='user')
    op.drop_column('user', 'spol')
    op.drop_column('user', 'prezime')
    op.drop_column('user', 'ime')
    # ### end Alembic commands ###
