"""users table

Revision ID: b57d314b20a3
Revises: 9d556144bfda
Create Date: 2019-01-25 10:30:47.139916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57d314b20a3'
down_revision = '9d556144bfda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mjesto', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_mjesto'), 'user', ['mjesto'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mjesto'), table_name='user')
    op.drop_column('user', 'mjesto')
    # ### end Alembic commands ###
