"""empty message

Revision ID: cbed1024dd71
Revises: 82f579fb4458
Create Date: 2019-02-01 01:38:51.685211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbed1024dd71'
down_revision = '82f579fb4458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tablica', sa.Column('prijava', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tablica', 'prijava')
    # ### end Alembic commands ###
