"""izlet table

Revision ID: f98f3f37dcb5
Revises: f884e85e4798
Create Date: 2019-01-25 12:15:38.063884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98f3f37dcb5'
down_revision = 'f884e85e4798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('izlet', sa.Column('mjesto', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('izlet', 'mjesto')
    # ### end Alembic commands ###
